### ISSUE TITLE
UnsupportedOperationException?

### ISSUE THREAD

**Issue by wolfomat** [monitorjbl/excel-streaming-reader#70] opened 2017-01-16 14:34 UTC
I'm using the lib since today and it's really nice. I can open very quickly large files.
My plan was to extract the first 10 rows, so that i can obtain the headers of the excel files (named ones)

When i am using:
	Workbook workbook = StreamingReader.builder().open(inputStream); // fails (@getSheet)
        Sheet sheet = workbook.getSheet (sheetName);

Where sheetName is "FirstQuarter" (which exists on the excel file), i'll get following exception:

java.lang.UnsupportedOperationException
	at com.monitorjbl.xlsx.impl.StreamingSheet.getRow(StreamingSheet.java:98)

am i missing something?

**Comment by monitorjbl** [comment] 2017-01-16 14:49
You can't use arbitrary seeking methods in this library. It's a streaming reader, so you have to loop through the rows yourself. To put it another way, this library is to POI as Iterator is to List. 

I'm going to close this issue as it's not a bug. However, if you have any other questions, feel free to keep commenting and I'll do my best to respond!

**Closed by monitorjbl** 2017-01-16 14:49 UTC

**Comment by koushikkolli** [comment] 2018-09-24 14:12
Hi 

InputStream is = new FileInputStream(file);
		Workbook workbook = StreamingReader.builder()
		        .rowCacheSize(10)            
		        .bufferSize(4096)  
		        .open(is); 
		
		for (Sheet sheet : workbook){
		    System.out.println(sheet.getSheetName());
		    for (Row r : sheet) {
		      for (Cell c : r) {
		       count=count+1;
		      }
		      break;
		    }
		  }
i am using above code for getting no of columns
the code is working fine if data is less but when data is more 
getting error 
Exception in thread "main" java.lang.NullPointerException
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.setFormatString(StreamingSheetReader.java:278)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.handleEvent(StreamingSheetReader.java:150)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.getRow(StreamingSheetReader.java:76)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.access$200(StreamingSheetReader.java:37)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.hasNext(StreamingSheetReader.java:412)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.<init>(StreamingSheetReader.java:406)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.iterator(StreamingSheetReader.java:378)
	at com.monitorjbl.xlsx.impl.StreamingSheet.iterator(StreamingSheet.java:49)

near  for (Row r : sheet)

**Comment by saravanansp26** [comment] 2019-01-18 09:09
Use Row r.getLastCellNum(). to get no of columns
